# Generated by Django 5.1.7 on 2025-06-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0003_procurementplan_stage'),
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('procurement_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='procurement.procurementplan')),
                ('specification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='specification.specification')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
            },
        ),
    ]
