# Generated by Django 5.1.7 on 2025-06-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='specification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='specification.specification'),
        ),
    ]
