# Generated by Django 5.1.7 on 2025-05-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0001_initial'),
        ('procurement', '0002_alter_procurementplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='procurement_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_projects', to='procurement.procurementplan'),
        ),
    ]
