// types/committee.ts
export type CommitteeTaskStatus = 'pending' | 'in_progress' | 'completed' | 'overdue';
export type CommitteeApprovalStatus = 'draft' | 'pending' | 'pending_review' | 'approved' | 'rejected';
export type DocumentStatus = 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected';

export interface CommitteeMember {
  id?: string;
  employeeId: string;
  name: string;
  email: string;
  department?: string;
  phone?: string;
  role?: 'member' | 'chairperson' | 'secretary';
  designation?: string;
  tasks?: string[];
}

export interface Committee {
  _id: string;
  name: string;
  purpose: string;
  committee_type: string;
  procurement_plan?: number | null;
  formation_date?: string | null;
  specification_submission_date?: string | null;
  review_date?: string | null;
  schedule?: string | null;
  should_notify?: boolean;
  formationLetterURL?: string | null;
  createdBy?: {
    _id: string;
    name: string;
    email: string;
    role: string;
    employeeId: string;
  };
  createdAt?: string;
  updatedAt?: string;
  membersList?: Array<{
    _id: string;
    employeeId: string;
    name: string;
    role: string;
    email: string;
    department?: string;
    designation?: string;
  }>;
  approvalStatus?: string;
}




// export type CommitteeTaskStatus = 'pending' | 'in_progress' | 'completed' | 'overdue';
// export type CommitteeApprovalStatus = 'draft' | 'pending' | 'pending_review' | 'approved' | 'rejected';
// export type DocumentStatus = 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected';

// export interface CommitteeTask {
//   id: number;
//   title: string;
//   description: string;
//   assignedTo: number; // memberId
//   dueDate: string;
//   status: CommitteeTaskStatus;
//   attachments?: File[];
//   comments?: string[];
// }

// // export interface CommitteeMember {
// //   id: number;
// //   employeeId: string;
// //   name: string;
// //   email: string;
// //   phone: string;
// //   designation: string;
// //   role: 'chairperson' | 'member' | 'secretary';
// //   department: string;
// //   tasks: CommitteeTask[];
// // }
// export interface CommitteeMember {
//   id?: string; // Optional, as it may be generated by the backend
//   employeeId: string;
//   name: string;
//   email: string;
//   department: string;
//   phone?: string; // Optional, as it may not be available
//   role?: string;
//   designation?: string;
//   tasks: string[];
// }
// export interface SpecificationReview {
//   id: number;
//   committeeId: number;
//   scheduledDate: string;
//   actualDate?: string;
//   minutes?: string;
//   status: DocumentStatus;
//   reviewers: CommitteeMember[];
//   documents: File[];
//   comments: string[];
// }


// export interface Committee {
//   _id: string;
//   name: string;
//   purpose: string;
//   committee_type: string;
//   procurement_plan?: number | null;
//   formation_date: string | null;
//   specification_submission_date?: string | null;
//   review_date?: string | null;
//   schedule?: string | null;
//   should_notify?: boolean;
//   formationLetterURL?: string | null;
//   createdBy?: {
//     _id: string;
//     name: string;
//     email: string;
//     role: string;
//     employeeId: string;
//   };
//   createdAt?: string;
//   updatedAt?: string;
//   membersList?: Array<{
//     _id: string;
//     employeeId: string;
//     name: string;
//     role: string;
//     email: string;
//     department?: string;
//     designation?: string;
//   }>;
//   approvalStatus?: string;
// } 

// ////###### START OF CODE
// // @/types/committee.ts
// // export interface Committee {
// //   _id: string;
// //   name?: string;
// //   purpose?: string;
// //   formationDate?: string | null;
// //   specificationSubmissionDate?: string | null;
// //   reviewDate?: string | null;
// //   should_notify?: boolean;
// //   members: CommitteeMember[];

// //   // members?: Array<{
// //   //   employeeId: string;
// //   //   name: string;
// //   //   department?: string;
// //   //   email?: string;
// //   //   role?: string;
// //   //   designation?: string | null;
// //   // }>;
// //   approvalStatus?: string;
// //   formationLetter?: string | null; // Changed to string | null
// //   schedule?: string | null;
// //   created_by?: {
// //     name: string;
// //     employeeId: string;
// //   };
// //   created_at?: string;
// //   updated_at?: string;
// //   [key: string]: any;
// // }

// //////#### END OF CODE
// // export interface Committee {
// //   _id: string;
// //   name: string;
// //   purpose: string;
// //   formationDate: string;
// //   specificationSubmissionDate?: string;
// //   reviewDate?: string;
// //   schedule?: string;
// //   members: CommitteeMember[];
// //   formationLetter?: {
// //     filename: string;
// //     path: string;
// //     originalname: string;
// //     mimetype: string;
// //     size: number;
// //   };
// //   createdBy: {
// //     _id: string;
// //     name: string;
// //     email: string;
// //     role: string;
// //     employeeId: string;
// //   };
// //   approvalStatus?: 'draft' | 'pending' | 'approved' | 'rejected';
// //   createdAt?: string;
// //   updatedAt?: string;
// // }

// export interface ReviewHistory {
//   id: number;
//   reviewDate: string;
//   reviewers: CommitteeMember[];
//   status: DocumentStatus;
//   minutes?: string;
//   documents: File[];
//   comments: string[];
//   nextReviewDate?: string;
// }
