# Generated by Django 5.1.7 on 2025-06-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('award_date', models.DateTimeField(auto_now_add=True)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/documents/')),
                ('status', models.CharField(choices=[('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='awarded', max_length=20)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bidding.bid')),
            ],
        ),
    ]
