# Generated by Django 5.1.7 on 2025-04-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('formation_date', models.DateField()),
                ('specification_submission_date', models.DateField()),
                ('review_date', models.DateField()),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('formation_letter', models.FileField(blank=True, null=True, upload_to='committees/formation_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('should_notify', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=20)),
            ],
        ),
    ]
