# Generated by Django 5.1.7 on 2025-04-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemembership',
            old_name='role',
            new_name='committee_role',
        ),
    ]
