# Generated by Django 5.1.7 on 2025-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_rename_role_committeemembership_committee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='formation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='specification_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
