# Generated by Django 5.1.7 on 2025-05-11 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_committee_formation_date_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='committee_type',
            field=models.CharField(choices=[('specification', 'Specification'), ('evaluation', 'Evaluation'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='committee',
            name='procurement_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='procurement.procurementplan'),
        ),
    ]
