# Generated by Django 5.1.7 on 2025-05-11 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_committee_committee_type_committee_procurement_plan'),
        ('procurement', '0002_alter_procurementplan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={},
        ),
        migrations.AddField(
            model_name='committee',
            name='approval_status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee_type',
            field=models.CharField(choices=[('specification', 'Specification'), ('evaluation', 'Evaluation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='committee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='formation_letter',
            field=models.FileField(blank=True, null=True, upload_to='formation_letters/'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='procurement_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='procurement.procurementplan'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='committee_role',
            field=models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('secretary', 'Secretary')], default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
