# Generated by Django 5.1.7 on 2025-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0006_alter_committee_options_committee_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
