# Generated by Django 5.1.7 on 2025-04-02 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_procurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementmember',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.procurement'),
        ),
        migrations.AddField(
            model_name='procurementmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurement',
            name='members',
            field=models.ManyToManyField(through='main_app.ProcurementMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='procurementmember',
            unique_together={('procurement', 'user')},
        ),
    ]
