# Generated by Django 5.1.7 on 2025-04-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
