# Generated by Django 5.1.7 on 2025-05-09 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('dept_index', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('q1', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], default='Planned', max_length=20)),
                ('q2', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], default='Planned', max_length=20)),
                ('q3', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], default='Planned', max_length=20)),
                ('q4', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy_number'],
            },
        ),
    ]
