# Generated by Django 5.1.7 on 2025-05-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_committee_committee_type_committee_procurement_plan'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='procurementplan',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='procurementplan',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='procurementplan',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='procurementplan',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='procurementplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='procurementplan',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committee.committee'),
        ),
        migrations.AlterField(
            model_name='procurementplan',
            name='department',
            field=models.CharField(choices=[('Wireline', 'Wireline'), ('Wireless', 'Wireless')], max_length=50),
        ),
        migrations.AlterField(
            model_name='procurementplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procurementplan',
            name='policy_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='QuarterlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('target_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procurement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_targets', to='procurement.procurementplan')),
            ],
            options={
                'unique_together': {('procurement_plan', 'quarter')},
            },
        ),
    ]
