# Generated by Django 5.1.7 on 2025-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_procurementplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementplan',
            name='stage',
            field=models.CharField(choices=[('planning', 'Procurement Planning'), ('specification', 'Specification Preparation'), ('tender', 'Tender Creation & Publication'), ('committee', 'Committee Formation'), ('bidding', 'Bidding Process'), ('evaluation', 'Bid Evaluation'), ('contract', 'Contract Award'), ('complaint', 'Complaint Handling'), ('management', 'Contract Management & Payment')], default='planning', max_length=20),
        ),
    ]
