# Generated by Django 5.1.7 on 2025-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='rolehierarchy',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
