# Generated by Django 5.1.7 on 2025-05-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('seniority', models.DateTimeField(blank=True, null=True)),
                ('retirement', models.DateTimeField(blank=True, null=True)),
                ('mno', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, default='Engineer', max_length=100, null=True),
        ),
    ]
